kind: pipeline
name: build-sekiro

steps:
- name: test
  image: golang
  commands:
  - go test ./handler
  - go build

services:
- name: redis
  image: redis
  ports:
  - 6379

- name: database
  image: mysql
  ports:
  - 3306
  environment:
    MYSQL_ROOT_PASSWORD: '123456'
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: '123456'
    MYSQL_DATABASE: sekiro_db