micro:
  command: api --handler=web
  image: microhq/micro:latest
  links:
    - api-user
    - api-score
    - api-chat
  ports:
    - "8080:8080"
api-user:
  build: ./api/user
api-score:
  build: ./api/score
api-chat:
  build: ./api/chat
