micro:
  command: --registry=consul --registry_address=129.211.75.241:8500 api --handler=web
  image: microhq/micro:latest
  ports:
    - "8080:8080"
api-user:
  build: ./api/user
  command: --registry=consul --registry_address=129.211.75.241:8500
api-score:
  build: ./api/score
  command: --registry=consul --registry_address=129.211.75.241:8500
api-chat:
  build: ./api/chat
  command: --registry=consul --registry_address=129.211.75.241:8500
