# default false
release_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"

# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[jwt]
secret = "jw45jw67dhy1"

[app]
name = "Sekiro Echo Web"

[server]
graceful = true
addr = ":8080"

[static]
# BINDATA,FILE(FILE Default)
type = "BINDATA"

[database]
name = "sekiro_db"
user_name = "root"
pwd  = "123456"
host = "database"
port = "3306"

[redis]
server = "127.0.0.1:6379"
pwd = "123456"

[opentracing]
disable = true


